Repository recurly/recurly-client-go, pull requests merged in 2020-05, with the labels that each got.

#28 Add github templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/question-or-other.md
Labels: documentation

#30 Add version scoped url to go.mod and install instructions
  .bumpversion.cfg
  README.md
  go.mod
  scripts/bump
Labels: bug

#32 Add three_d_secure_action_token_id to TransactionError
  error.go
Labels: enhancement

#33 Fix pagination example
  README.md
Labels: documentation
